## Initial Data Loading

In [ ]:
import pandas as pd
df = pd.read_csv('/content/session4_dummy_students_data.csv.xls')

## Initial Data Exploration

### Display First Few Rows

In [ ]:
print('First 5 rows of the DataFrame:')
display(df.head())

First 5 rows of the DataFrame:

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82
1,102,Diya,16,Delhi,91,88,94,96,11,10,93
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60
3,104,Meera,16,Noida,72,79,81,89,7,8,78
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45

### Check DataFrame Shape

In [ ]:
print('\nShape of the DataFrame:')
display(df.shape)

Shape of the DataFrame:

(20, 11)

### Get DataFrame Information (Data Types, Non-Null Counts)

In [ ]:
print('\nInformation about the DataFrame (data types, non-null values):')
display(df.info())

Information about the DataFrame (data types, non-null values):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             20 non-null     int64
 1   name                   20 non-null     object
 2   age                    20 non-null     int64
 3   city                   20 non-null     object
 4   math                   20 non-null     int64
 5   science                20 non-null     int64
 6   english                20 non-null     int64
 7   attendance_percent     20 non-null     int64
 8   study_hours_per_week   20 non-null     int64
 9   assignments_submitted  20 non-null     int64
 10  final_project_score    20 non-null     int64
dtypes: int64(9), object(2)
memory usage: 1.8+ KB

None

### View Descriptive Statistics

In [ ]:
print('\nDescriptive statistics of the DataFrame:')
display(df.describe())

Descriptive statistics of the DataFrame:

,student_id,age,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,110.50000,16.450000,69.500000,72.350000,72.200000,83.850000,7.250000,7.750000,73.650000
std,5.91608,0.510418,18.446223,15.383775,17.157475,11.089469,3.092861,1.915999,17.439444
min,101.00000,16.000000,35.000000,45.000000,42.000000,62.000000,2.000000,4.000000,39.000000
25%,105.75000,16.000000,57.250000,60.000000,59.500000,76.500000,5.000000,6.000000,62.250000
50%,110.50000,16.000000,73.000000,74.500000,75.500000,87.500000,7.500000,8.000000,78.500000
75%,115.25000,17.000000,84.250000,85.250000,86.000000,92.500000,9.250000,9.250000,87.250000
max,120.00000,17.000000,95.000000,93.000000,96.000000,98.000000,13.000000,10.000000,96.000000

## Intermediate NumPy Array Creation

### Math Scores as NumPy Array

In [ ]:
math_scores_np = df['math'].to_numpy()
print(math_scores_np)

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]

### Science Scores as NumPy Array

In [ ]:
science_scores_np = df['science'].to_numpy()
print(science_scores_np)

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]

### English Scores as NumPy Array

In [ ]:
english_scores_np = df['english'].to_numpy()
print(english_scores_np)

[69 94 58 81 47 90 66 89 51 85 72 79 42 91 60 96 65 83 46 80]

### Calculate Average Score (Using NumPy Arrays)

In [ ]:
avg=(math_scores_np+science_scores_np+english_scores_np)/3
print(avg)

[77.         91.         58.         77.33333333 46.33333333 90.33333333
 66.66666667 92.         52.         81.33333333 67.33333333 78.
 40.66666667 88.66666667 57.33333333 92.66666667 65.         82.66666667
 46.         76.66666667]

### Identify Students with Average Score Greater Than 85

In [ ]:
students_above_85_avg = df[avg > 85]['name']
print('Students with average score greater than 85:')
print(students_above_85_avg.to_string(index=False))

Students with average score greater than 85:
  Diya
  Sara
Ananya
 Priya
  Riya

## Adding Calculated Columns to DataFrame

### Add 'average' Column to DataFrame

In [ ]:
df['average'] = df[['math', 'science', 'english']].mean(axis=1)
df

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333
5,106,Sara,16,Delhi,88,93,90,97,10,10,95,90.333333
6,107,Ishaan,17,Mathura,64,70,66,82,6,7,69,66.666667
7,108,Ananya,16,Noida,95,92,89,94,12,10,91,92.000000
8,109,Vivaan,17,Mumbai,48,57,51,71,4,6,55,52.000000
9,110,Tara,16,Delhi,83,76,85,90,9,9,86,81.333333
10,111,Arjun,17,Mathura,67,63,72,80,6,8,70,67.333333
11,112,Nisha,16,Noida,74,81,79,88,8,8,80,78.000000
12,113,Dev,17,Mumbai,35,45,42,62,2,4,39,40.666667
13,114,Priya,16,Delhi,89,86,91,95,10,10,92,88.666667
14,115,Kunal,17,Mathura,58,54,60,77,5,6,63,57.333333
15,116,Riya,16,Noida,92,90,96,98,13,10,96,92.666667
16,117,Om,17,Mumbai,61,69,65,79,6,7,68,65.000000
17,118,Aditi,16,Delhi,80,85,83,91,9,9,84,82.666667
18,119,Yash,17,Mathura,43,49,46,66,3,5,48,46.000000
19,120,Sneha,16,Noida,77,73,80,87,8,8,79,76.666667

### Add 'result' Column (Pass/Fail) to DataFrame

In [ ]:
df['result'] = df['average'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
df

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average,result
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000,Pass
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000,Pass
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000,Pass
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333,Pass
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333,Pass
5,106,Sara,16,Delhi,88,93,90,97,10,10,95,90.333333,Pass
6,107,Ishaan,17,Mathura,64,70,66,82,6,7,69,66.666667,Pass
7,108,Ananya,16,Noida,95,92,89,94,12,10,91,92.000000,Pass
8,109,Vivaan,17,Mumbai,48,57,51,71,4,6,55,52.000000,Pass
9,110,Tara,16,Delhi,83,76,85,90,9,9,86,81.333333,Pass
10,111,Arjun,17,Mathura,67,63,72,80,6,8,70,67.333333,Pass
11,112,Nisha,16,Noida,74,81,79,88,8,8,80,78.000000,Pass
12,113,Dev,17,Mumbai,35,45,42,62,2,4,39,40.666667,Pass
13,114,Priya,16,Delhi,89,86,91,95,10,10,92,88.666667,Pass
14,115,Kunal,17,Mathura,58,54,60,77,5,6,63,57.333333,Pass
15,116,Riya,16,Noida,92,90,96,98,13,10,96,92.666667,Pass
16,117,Om,17,Mumbai,61,69,65,79,6,7,68,65.000000,Pass
17,118,Aditi,16,Delhi,80,85,83,91,9,9,84,82.666667,Pass
18,119,Yash,17,Mathura,43,49,46,66,3,5,48,46.000000,Pass
19,120,Sneha,16,Noida,77,73,80,87,8,8,79,76.666667,Pass

## Summary Statistics

### Calculate Class Average

In [ ]:
class_average = df['average'].mean()
print(f"Class Average: {class_average:.2f}")

Class Average: 71.35

### Determine Highest and Lowest Averages

In [ ]:
highest_average = df['average'].max()
lowest_average = df['average'].min()

print(f"Highest Average: {highest_average:.2f}")
print(f"Lowest Average: {lowest_average:.2f}")

Highest Average: 92.67
Lowest Average: 40.67

### Top Student(s) Based on Average Score

In [ ]:
top_students = df[df['average'] == highest_average]
print("Top Student(s):")
print(top_students)

Top Student(s):
    student_id  name  age   city  math  science  english  attendance_percent  \
15         116  Riya   16  Noida    92       90       96                  98

    study_hours_per_week  assignments_submitted  final_project_score  \
15                    13                     10                   96

      average result
15  92.666667   Pass

## Specific Student Group Analysis

### Students with Low Attendance (Below 75%)

In [ ]:
low_attendance = df[df['attendance_percent'] < 75]
print("Students with attendance below 75:")
print(low_attendance)

Students with attendance below 75:
    student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47
8          109  Vivaan   17   Mumbai    48       57       51
12         113     Dev   17   Mumbai    35       45       42
18         119    Yash   17  Mathura    43       49       46

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5
8                   71                     4                      6
12                  62                     2                      4
18                  66                     3                      5

    final_project_score    average result
4                    45  46.333333   Pass
8                    55  52.000000   Pass
12                   39  40.666667   Pass
18                   48  46.000000   Pass

### Students with Fewer Than 6 Assignments Submitted

In [ ]:
few_assignments = df[df['assignments_submitted'] < 6]
print("Students with fewer than 6 assignments:")
print(few_assignments)

Students with fewer than 6 assignments:
    student_id   name  age     city  math  science  english  \
4          105  Rohan   17   Mumbai    40       52       47
12         113    Dev   17   Mumbai    35       45       42
18         119   Yash   17  Mathura    43       49       46

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5
12                  62                     2                      4
18                  66                     3                      5

    final_project_score    average result
4                    45  46.333333   Pass
12                   39  40.666667   Pass
18                   48  46.000000   Pass

## Exporting Results

### Save Processed DataFrame to CSV

In [ ]:
df.to_csv('session4_student_report.csv', index=False)
print("Report successfully saved!")

Report successfully saved!